config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # root 'home#index'
  root "friends#index"
  get "home/index"
  get "home/about"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to:user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  #authenticate na hole only friend list and details dekte parbe.
  before_action :correct_user, only: [:edit, :destroy, :update]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id]) #id = params[:id] perameter er id , see note
    redirect_to friends_path, notice: "You are not allowed to do this!" if @friend.nil?
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name , class:'form-control' %>
  </div>
  <div  class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:'form-control'  %>
  </div>
  <div  class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:'form-control'  %>
  </div>
  <div  class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone , class:'form-control' %>
  </div>
  <div  class="form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:'form-control'  %>
  </div>
  <div  class="form-group">
    <%= form.number_field :user_id,id: :friend_user_id, value:current_user.id,type: :hidden  %>
  </div  class="form-group">
  <div  class="form-group">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<% count = 0 %>
<div id="<%= dom_id friend %>">
  <% if current_user==friend.user%>
    <% count+=1 %>
    <tr>
      <td> <%= count %> </td>
      <td><%= link_to  friend.first_name+" " + friend.last_name, friend %></td>
      <td> <%= friend.email %></td>
      <td> <%= friend.phone %></td>
      <td> <%= friend.twitter %></td>
      <td>
        <%= button_to 'Remove', friend, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-danger btn-sm" %>
      </td>
    </tr>
  <%end%>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Show this friend", @friend,class:'btn btn-secondary' %>
  <%= link_to "Back to friends", friends_path,class:'btn btn-secondary' %>
</div>

app/views/friends/index.html.erb
<%if user_signed_in? %>
  <h1>Friends</h1>
  <div id="friends">
    <table class="table table-striped table-bordered table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">SL</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Phone</th>
          <th scope="col">Twitter</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <%= render friend %>
        <% end %>
        <tbody/>
        <table/>
      </div>
      <%= link_to "New friend", new_friend_path, class:'btn btn-secondary' %>
    <%else%>
      <h1>Welcome Home</h1>
    <%end%>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br>
<%= render "form", friend: @friend %>
<%= link_to "Back to friends", friends_path,class:'btn btn-secondary' %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.twitter %>
  </p>
  <br/>
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Curd App", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path,method: :delete, class: "nav-link" %>
        </li>
      <%else%>
        <li class="nav-item">
          <%= link_to "SignUp", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Welcome to about!<h1>

app/views/home/index.html.erb
<h1>Welcome Home</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>    
    <%= javascript_pack_tag "application","data-turbolinks-track": "reload":%>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class='container'>
      <%if notice%>
        <br>
        <%= render 'layouts/alerts'%>
        <br>
      <%end%>
      <%= yield %>
      <div/>
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
  </html>